;/*FB_PKG_DELIM*/

__d("FBWebBloksSurveyRtfTextQuestion",["WebBloksStyle","dompurify","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){var e,s=e||(e=o("react")),u=e.useMemo;function c(e){var t=o("react-compiler-runtime").c(15),n=e.externalStyle,a=e.node,i=o("WebBloksStyle").useStyle(a,n),l=i.style,u=i.wrapper,c=i.wrapperProps,d;t[0]!==a?(d=a.get("html"),t[0]=a,t[1]=d):d=t[1];var m=d,p;t[2]!==m?(p=r("dompurify").sanitize(m!=null?m:""),t[2]=m,t[3]=p):p=t[3];var _=p,f;t[4]!==_?(f={__html:_},t[4]=_,t[5]=f):f=t[5];var g;t[6]!==l?(g=babelHelpers.extends({display:"block"},l),t[6]=l,t[7]=g):g=t[7];var h;t[8]!==f||t[9]!==g||t[10]!==c?(h=s.jsx("div",babelHelpers.extends({},c,{className:o("WebBloksStyle").WebBloksStyles.container,dangerouslySetInnerHTML:f,style:g})),t[8]=f,t[9]=g,t[10]=c,t[11]=h):h=t[11];var y;return t[12]!==h||t[13]!==u?(y=u(h),t[12]=h,t[13]=u,t[14]=y):y=t[14],y}l.default=c}),98);
__d("JSResource",["JSResourceReferenceImpl"],(function(t,n,r,o,a,i,l){var e={};function s(t,n){e[t]=n}function u(t){return e[t]}function c(e){var t=e,n=u(t);if(n)return n;var o=new(r("JSResourceReferenceImpl"))(t);return s(t,o),o}c.loadAll=r("JSResourceReferenceImpl").loadAll,l.default=c}),98);
__d("getEarlyResources",[],(function(t,n,r,o,a,i){"use strict";function e(){return Array.from(document.querySelectorAll("head script[data-bootloader-hash]"))}i.default=e}),66);
__d("getInvisibleIframe",["cr:6114"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t){var r=n("cr:6114").create("iframe",{width:0,height:0,frameborder:0,scrolling:"no","aria-hidden":"true",style:{opacity:0,pointerEvents:"none",position:"absolute"}});e!==void 0&&r.setAttribute("src",e),t&&(r.onload=t),n("cr:6114").appendContent(document.body,r);function o(e){e.__annotator=function(e){return e},e.__d_stub=[],e.__d=function(){e.__d_stub.push(arguments)}}function a(e){e.onerror=function(t,n,r,o,a){return!0}}return o(r.contentWindow),a(r.contentWindow),r}l.default=e}),98);
__d("ResourcesRefetcher",["Arbiter","PageEvents","cr:6114","getEarlyResources","getInvisibleIframe"],(function(t,n,r,o,a,i,l){"use strict";var e=0,s=0,u=null;function c(t){var r=d();e=t.length;for(var o=0;o<t.length;o++){var a=n("cr:6114").create("script",{src:t[o].getAttribute("src"),crossorigin:"anonymous"});a.onload=function(){p()},n("cr:6114").appendContent(r.contentDocument.head,a)}}function d(){return u===null&&(u=r("getInvisibleIframe")()),u}function m(e){r("Arbiter").subscribeOnce(r("PageEvents").BIGPIPE_ONLOAD,function(){var t=r("getEarlyResources")();e.allEF||(t=t.slice(0,1)),c(t)})}function p(){++s<e||u&&(n("cr:6114").remove(u),u=null,s=0)}l.refetchScripts=c,l._getIframe=d,l.refetchOnLoad=m,l.checkForFinished=p}),98);
__d("ServiceWorkerURLCleaner",[],(function(t,n,r,o,a,i){var e=/sw_fnr_id=\d+&?/,l=/fnr_t=\d+&?/,s=!1,u=!1;function c(){if(s)return u;if(s=!0,location.search&&e.test(location.search)&&(u=!0,history!==void 0&&typeof history.replaceState=="function")){var t=location.toString().replace(e,"").replace(l,"").replace(/\?$/,"");history.replaceState({},document.title,t)}return u}i.removeRedirectID=c}),66);
__d("VultureJSGating",["justknobx"],(function(t,n,r,o,a,i,l){"use strict";var e=!1;function s(){e=!0}function u(){return e?!1:r("justknobx")._("2635")}l.__DO_NOT_USE_DISABLE_VULTURE_JS_LOGGING=s,l.isLoggingEnabled=u}),98);
__d("XDeviceBasedLoginSaveCredentialWithNonceAsyncControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/login/device-based/scocct/async/",Object.freeze({}),void 0),s=e;l.default=s}),98);
__d("WebBloksCAASaveCredentialWithNonce",["XAsyncRequest","XDeviceBasedLoginSaveCredentialWithNonceAsyncControllerRouteBuilder"],(function(t,n,r,o,a,i,l){function e(e,t,n,o,a){var i=r("XDeviceBasedLoginSaveCredentialWithNonceAsyncControllerRouteBuilder").buildUri({}).toString();new(r("XAsyncRequest"))(i).setMethod("POST").setAutoProcess(!1).setData({eud:n}).setPayloadHandler(function(n){e.executeCatch(n.success?o:a,[t])}).setErrorHandler(function(n){e.executeCatch(a,[t])}).send()}l.default=e}),98);
__d("logForCrashUtils",[],(function(t,n,r,o,a,i){"use strict";var e={RST_JS_STACK_KEY_PREFIX:"#rst-js-stack"},l=e;i.default=l}),66);
__d("objectEntries",[],(function(t,n,r,o,a,i){function e(e){return Object.entries(e)}i.default=e}),66);
__d("vulture",["ExecutionEnvironment","FBLogger","JSResource","VultureJSGating","asyncToGeneratorRuntime","clearTimeout","objectEntries","requireDeferred","setTimeout"],(function(t,n,r,o,a,i,l){"use strict";var e,s=0,u=1e4,c=null;r("requireDeferred")("bumpVultureJSHash").__setRef("vulture").onReadyImmediately(function(e){c=e,b()});var d=!1,m=!1,p=null,_=new Map,f=[],g=12e4;function h(e){var t=_.get(e);t===s||c==null||(t==null?c(e,1):Math.floor(Math.random()*t)===0&&c(e,t))}function y(e){f.push(e)}function C(){p!=null&&(r("clearTimeout")(p),p=null),m=!1,d=!0,b()}function b(){if(d&&c!=null)for(;f.length>0;){var e=f.pop();e!=null&&h(e)}}function v(){r("JSResource")("VultureJSSampleRatesLoader").__setRef("vulture").load().then((function(){var e=n("asyncToGeneratorRuntime").asyncToGenerator(function*(e){var t=yield e.loadSampleRates();for(var n of r("objectEntries")(t)){var o=n[0],a=n[1];_.set(o,a)}});return function(t){return e.apply(this,arguments)}})()).catch(function(e){r("FBLogger")("vulture_js","sample_rate_load_timeout").catching(e).mustfix("Failed to fetch sample rates:  %s",e.getMessage())}).finally(C)}function S(){m||(m=!0,(e||(e=r("ExecutionEnvironment"))).canUseDOM?(p=r("setTimeout")(function(){C(),r("FBLogger")("vulture_js","sample_rate_load_timeout").warn("Timed out attemping to fetch VultureJS sample rates")},g),r("setTimeout")(v,u)):v())}function R(e){o("VultureJSGating").isLoggingEnabled()&&(d&&c!=null?h(e):(y(e),S()))}l.default=R}),98);